#! /bin/bash

# Setup
source .road-trip-commands

# Install backend python stuff
echo "Configuring $(func 'python') virtualenv..."
virtualenv --system-site-packages backend
source backend/bin/activate
pip install Flask
pip install nltk
pip install oauth2

# Get out of python env
deactivate
echo "Done installing $(func 'python') packages"

echo "$(success 'Done with setup!')"
