#!/bin/bash
trap 'killall' INT

killall() {
    trap '' INT TERM     # ignore INT and TERM while shutting down
    echo "[Road Trip] Shutting down..."     # added double quotes
    kill -TERM 0         # fixed order, send TERM not INT
    wait
    echo "[Road Trip] All cleaned up."
}

export PATH="./npm-global/bin/:$PATH"
source backend/bin/activate
cd code
python app.py --gui & # Run backend server
cd ..
cd html
gulp & # Run gulp
cd ..
deactivate

echo "[Road Trip] Starting up... Should load python and gulp"

cat # wait forever
