#!/bin/bash

killall() {
    trap '' INT TERM     # ignore INT and TERM while shutting down
    echo "Shutting down..."     # added double quotes
    kill -TERM 0         # fixed order, send TERM not INT
    wait
    echo "$(success 'Quit cleanly')"
}

# Setup
source .road-trip-commands
export PATH="./npm-global/bin/:$PATH"
echo "Starting servers..."
source backend/bin/activate

# Python server
echo "Starting $(func 'python') backend server..."
cd code
(python app.py --gui 3>&1 1>&2- 2>&3-) | adddate &
cd ..

# Gulp server
echo "Starting $(func 'gulp') for frontend..."
cd html
gulp & # Run gulp
cd ..

# Out of environment
deactivate

# Killall activated
trap 'killall' INT
cat # wait forever
