#! /bin/bash

# Install node stuff
npm config set prefix $(pwd)/npm-global
export PATH="./npm-global/bin/:$PATH"
npm install -g gulp
npm install -g bower
cd html && npm install
../npm-global/bin/bower install
cd ..
npm config delete prefix

# Install backend python stuff
virtualenv backend
source backend/bin/activate
pip install Flask
pip install nltk
pip install oauth2
deactivate

echo
echo "[Road Trip] All installed! To run, do ./run from this folder"
