#! /bin/bash

# Install node stuff
#npm config set prefix $(pwd)/npm-global
#npm install -g gulp
cd html
npm install
bower install
cd ../

# Install backend python stuff
virtualenv backend
source backend/bin/activate
pip install Flask
pip install nltk
pip install oauth2
deactivate

echo
echo "[Road Trip] All installed! To run, do ./run from this folder"
